agents:
  - id: agent_a
    name: A Agent
    description: 適合查詢一般網路摘要、影片剪輯教學等資訊。
    example_queries:
      - 請幫我查一下影片剪輯教學
      - 什麼是 YouTuber？

  - id: agent_b
    name: B Agent
    description: 適合查詢 B 網站的專業資料或特定主題。
    example_queries:
      - B 網站有什麼新消息？

routes:
  default:
    steps:
      - agent: agent_a
        input: "{{query}}"
      - agent: agent_b
        input: "{{query}}" 